{'response': <Response [200]>,
 'events': [{
 'match_id': '208975',
 'country_id': '6',
 'country_name': 'Spain',
 'league_id': '302',
 'league_name': 'La Liga',
 'match_date': '2023-10-21',
 'match_status': '63',
 'match_time': '14:00',
 'match_hometeam_id': '153',
 'match_hometeam_name': 'Real Sociedad',
 'match_hometeam_score': '0',
 'match_awayteam_name': 'Mallorca',
 'match_awayteam_id': '7285',
 'match_awayteam_score': '0',
 'match_hometeam_halftime_score': '0',
 'match_awayteam_halftime_score': '0',
 'match_hometeam_extra_score': '',
 'match_awayteam_extra_score': '',
 'match_hometeam_penalty_score': '',
 'match_awayteam_penalty_score': '',
 'match_hometeam_ft_score': '',
 'match_awayteam_ft_score': '',
 'match_hometeam_system': '4-4-2',
 'match_awayteam_system': '5-3-2',
 'match_live': '1',
 'match_round': '10',
 'match_stadium': 'Reale Arena,San Sebastian',
 'match_referee': 'Jorge Figueroa Vazquez,Spain',
 'team_home_badge': 'https://apiv3.apifootball.com/badges/153_real-sociedad.jpg',
 'team_away_badge': 'https://apiv3.apifootball.com/badges/7285_mallorca.jpg',
 'league_logo': 'https://apiv3.apifootball.com/badges/logo_leagues/302_la-liga.png',
 'country_logo': 'https://apiv3.apifootball.com/badges/logo_country/6_spain.png',
 'league_year': '2023/2024',
 'fk_stage_key': '402',
 'stage_name': 'Current',
 'goalscorer': [],
 'cards': [{'time': '15',
 'home_fault': '',
 'card': 'yellow card',
 'away_fault': 'J. Copete',
 'info': '',
 'home_player_id': '',
 'away_player_id': '2852751202',
 'score_info_time': '1st Half'},
 {'time': '41',
 'home_fault': '',
 'card': 'yellow card',
 'away_fault': 'T. Lato',
 'info': '',
 'home_player_id': '',
 'away_player_id': '1808297985',
 'score_info_time': '1st Half'},
 {'time': '43',
 'home_fault': '',
 'card': 'yellow card',
 'away_fault': 'A. Sanchez',
 'info': '',
 'home_player_id': '',
 'away_player_id': '1403983417',
 'score_info_time': '1st Half'}],
 'substitutions': {'home': [{'time': '46',
 'substitution': 'A. Zakharyan | A. Barrenetxea',
 'substitution_player_id': '3969964974 | 1844481783'}],
 'away': []},
 'lineup': {'home': {'starting_lineups': [{'lineup_player': 'Álex Remiro',
 'lineup_number': '1',
 'lineup_position': '1',
 'player_key': '966563824'},
 {'lineup_player': 'Aritz Elustondo',
 'lineup_number': '6',
 'lineup_position': '2',
 'player_key': '3802625738'},
 {'lineup_player': 'Igor Zubeldia',
 'lineup_number': '5',
 'lineup_position': '3',
 'player_key': '2951793647'},
 {'lineup_player': 'Jon Pacheco',
 'lineup_number': '20',
 'lineup_position': '4',
 'player_key': '2603640050'},
 {'lineup_player': 'Aihen Muñoz',
 'lineup_number': '3',
 'lineup_position': '5',
 'player_key': '2137825202'},
 {'lineup_player': 'Brais Méndez',
 'lineup_number': '23',
 'lineup_position': '6',
 'player_key': '2277700578'},
 {'lineup_player': 'Martín Zubimendi',
 'lineup_number': '4',
 'lineup_position': '7',
 'player_key': '2384169530'},
 {'lineup_player': 'Mikel Merino',
 'lineup_number': '8',
 'lineup_position': '8',
 'player_key': '2208713585'},
 {'lineup_player': 'Arsen Zakharyan',
 'lineup_number': '12',
 'lineup_position': '9',
 'player_key': '3969964974'},
 {'lineup_player': 'Carlos Fernández',
 'lineup_number': '9',
 'lineup_position': '10',
 'player_key': '1516457249'},
 {'lineup_player': 'Mikel Oyarzabal',
 'lineup_number': '10',
 'lineup_position': '11',
 'player_key': '3111173085'}],
 'substitutes': [{'lineup_player': 'Unai Marrero',
 'lineup_number': '32',
 'lineup_position': '0',
 'player_key': '2104475507'},
 {'lineup_player': 'Aitor Fraga',
 'lineup_number': '37',
 'lineup_position': '0',
 'player_key': '63840437'},
 {'lineup_player': 'Urko González',
 'lineup_number': '26',
 'lineup_position': '0',
 'player_key': '2341737935'},
 {'lineup_player': 'Robin Le Normand',
 'lineup_number': '24',
 'lineup_position': '0',
 'player_key': '4205767909'},
 {'lineup_player': 'Hamari Traore',
 'lineup_number': '18',
 'lineup_position': '0',
 'player_key': '1241687481'},
 {'lineup_player': 'Beñat Turrientes',
 'lineup_number': '22',
 'lineup_position': '0',
 'player_key': '2166347623'},
 {'lineup_player': 'Jon Magunazelaia',
 'lineup_number': '28',
 'lineup_position': '0',
 'player_key': '3054200992'},
 {'lineup_player': 'Jon Ander Olasagasti',
 'lineup_number': '16',
 'lineup_position': '0',
 'player_key': '4270833326'},
 {'lineup_player': 'Takefusa Kubo',
 'lineup_number': '14',
 'lineup_position': '0',
 'player_key': '1309668062'},
 {'lineup_player': 'Umar Sadiq',
 'lineup_number': '19',
 'lineup_position': '0',
 'player_key': '712365679'},
 {'lineup_player': 'Mohamed-Ali Cho',
 'lineup_number': '11',
 'lineup_position': '0',
 'player_key': '1466516134'},
 {'lineup_player': 'Ander Barrenetxea',
 'lineup_number': '7',
 'lineup_position': '0',
 'player_key': '1844481783'}],
 'coach': [{'lineup_player': 'Imanol Alguacil',
 'lineup_number': '',
 'lineup_position': '',
 'player_key': '2613828720'}],
 'missing_players': []},
 'away': {'starting_lineups': [{'lineup_player': 'Predrag Rajkovic',
 'lineup_number': '1',
 'lineup_position': '1',
 'player_key': '75436180'},
 {'lineup_player': 'Giovanni González',
 'lineup_number': '20',
 'lineup_position': '2',
 'player_key': '3324956053'},
 {'lineup_player': 'Martin Valjent',
 'lineup_number': '24',
 'lineup_position': '3',
 'player_key': '1409205496'},
 {'lineup_player': 'Matija Nastasic',
 'lineup_number': '2',
 'lineup_position': '4',
 'player_key': '514774676'},
 {'lineup_player': 'José Copete',
 'lineup_number': '6',
 'lineup_position': '5',
 'player_key': '2852751202'},
 {'lineup_player': 'Toni Lato',
 'lineup_number': '3',
 'lineup_position': '6',
 'player_key': '1808297985'},
 {'lineup_player': 'Antonio Sánchez',
 'lineup_number': '18',
 'lineup_position': '7',
 'player_key': '1403983417'},
 {'lineup_player': 'Samuel Costa',
 'lineup_number': '12',
 'lineup_position': '8',
 'player_key': '412597878'},
 {'lineup_player': 'Dani Rodríguez',
 'lineup_number': '14',
 'lineup_position': '9',
 'player_key': '4136045301'},
 {'lineup_player': 'Cyle Larin',
 'lineup_number': '17',
 'lineup_position': '10',
 'player_key': '1651223396'},
 {'lineup_player': 'Vedat Muriqi',
 'lineup_number': '7',
 'lineup_position': '11',
 'player_key': '1468412695'}],
 'substitutes': [{'lineup_player': 'Dominik Greif',
 'lineup_number': '13',
 'lineup_position': '0',
 'player_key': '2196456062'},
 {'lineup_player': 'Iván Cuéllar',
 'lineup_number': '25',
 'lineup_position': '0',
 'player_key': '545801167'},
 {'lineup_player': 'Jaume Costa',
 'lineup_number': '11',
 'lineup_position': '0',
 'player_key': '2975945013'},
 {'lineup_player': 'Siebe Van Der Heyden',
 'lineup_number': '4',
 'lineup_position': '0',
 'player_key': '3838422988'},
 {'lineup_player': 'Yuzún Ley',
 'lineup_number': '31',
 'lineup_position': '0',
 'player_key': '3433429528'},
 {'lineup_player': 'David López',
 'lineup_number': '27',
 'lineup_position': '0',
 'player_key': '764261089'},
 {'lineup_player': 'Daniel Luna',
 'lineup_number': '33',
 'lineup_position': '0',
 'player_key': '1984247274'},
 {'lineup_player': 'Omar Mascarell',
 'lineup_number': '5',
 'lineup_position': '0',
 'player_key': '2805489478'},
 {'lineup_player': 'Manu Morlanes',
 'lineup_number': '8',
 'lineup_position': '0',
 'player_key': '1426253949'},
 {'lineup_player': 'Amath Ndiaye',
 'lineup_number': '23',
 'lineup_position': '0',
 'player_key': '320119617'},
 {'lineup_player': 'Javi Llabrés',
 'lineup_number': '19',
 'lineup_position': '0',
 'player_key': '1756111889'},
 {'lineup_player': 'Abdón Prats',
 'lineup_number': '9',
 'lineup_position': '0',
 'player_key': '2310319274'}],
 'coach': [{'lineup_player': 'J. Aguirre',
 'lineup_number': '',
 'lineup_position': '',
 'player_key': '3738143634'}],
 'missing_players': []}},
 'statistics': [{'type': 'Throw In',
 'home': '0',
 'away': '0'},
 {'type': 'Free Kick',
 'home': '0',
 'away': '0'},
 {'type': 'Goal Kick',
 'home': '0',
 'away': '0'},
 {'type': 'Penalty',
 'home': '0',
 'away': '0'},
 {'type': 'Substitution',
 'home': '0',
 'away': '0'},
 {'type': 'Attacks',
 'home': '48',
 'away': '38'},
 {'type': 'Dangerous Attacks',
 'home': '20',
 'away': '15'},
 {'type': 'On Target',
 'home': '2',
 'away': '3'},
 {'type': 'Off Target',
 'home': '4',
 'away': '3'},
 {'type': 'Shots Total',
 'home': '6',
 'away': '6'},
 {'type': 'Shots On Goal',
 'home': '2',
 'away': '3'},
 {'type': 'Shots Off Goal',
 'home': '2',
 'away': '2'},
 {'type': 'Shots Blocked',
 'home': '2',
 'away': '1'},
 {'type': 'Shots Inside Box',
 'home': '2',
 'away': '5'},
 {'type': 'Shots Outside Box',
 'home': '4',
 'away': '1'},
 {'type': 'Fouls',
 'home': '6',
 'away': '10'},
 {'type': 'Corners',
 'home': '1',
 'away': '3'},
 {'type': 'Offsides',
 'home': '0',
 'away': '1'},
 {'type': 'Ball Possession',
 'home': '59%',
 'away': '41%'},
 {'type': 'Yellow Cards',
 'home': '0',
 'away': '3'},
 {'type': 'Saves',
 'home': '3',
 'away': '2'},
 {'type': 'Passes Total',
 'home': '202',
 'away': '134'},
 {'type': 'Passes Accurate',
 'home': '157',
 'away': '89'}],
 'statistics_1half': [{'type': 'Throw In',
 'home': '0',
 'away': '0'},
 {'type': 'Free Kick',
 'home': '0',
 'away': '0'},
 {'type': 'Goal Kick',
 'home': '0',
 'away': '0'},
 {'type': 'Penalty',
 'home': '0',
 'away': '0'},
 {'type': 'Substitution',
 'home': '1',
 'away': '0'},
 {'type': 'Attacks',
 'home': '49',
 'away': '39'},
 {'type': 'Dangerous Attacks',
 'home': '20',
 'away': '16'},
 {'type': 'On Target',
 'home': '2',
 'away': '3'},
 {'type': 'Off Target',
 'home': '4',
 'away': '4'},
 {'type': 'Shots Total',
 'home': '6',
 'away': '7'},
 {'type': 'Shots On Goal',
 'home': '2',
 'away': '3'},
 {'type': 'Shots Off Goal',
 'home': '2',
 'away': '3'},
 {'type': 'Shots Blocked',
 'home': '2',
 'away': '1'},
 {'type': 'Shots Inside Box',
 'home': '2',
 'away': '6'},
 {'type': 'Shots Outside Box',
 'home': '4',
 'away': '1'},
 {'type': 'Fouls',
 'home': '7',
 'away': '10'},
 {'type': 'Corners',
 'home': '1',
 'away': '3'},
 {'type': 'Offsides',
 'home': '0',
 'away': '1'},
 {'type': 'Ball Possession',
 'home': '58%',
 'away': '42%'},
 {'type': 'Yellow Cards',
 'home': '0',
 'away': '3'},
 {'type': 'Saves',
 'home': '3',
 'away': '2'},
 {'type': 'Passes Total',
 'home': '204',
 'away': '138'},
 {'type': 'Passes Accurate',
 'home': '157',
 'away': '91'}]}]}